server:
  name: "project-project"
  addr: "0.0.0.0:8081"
zap:
  debugFileName: "/logs/debug/project-debug.log"
  infoFileName: "/logs/info/project-info.log"
  warnFileName: "/logs/error/project-error.log"
  maxSize: 500
  maxAge: 28
  maxBackups: 3
redis:
  host: "redis"
  port: 6379
  password: ""
  db: 0
grpc:
  addr: "project:8882"
  name: "project"
  version: "1.0.0"
  weight: 2
etcd:
  addrs:
    - "etcd:2379"
mysql:
  username: root
  host: mysql
  port: 3306
  db: msproject
jwt:
  accessExp: 7
  refreshExp: 14
